repos:
- repo: git@github.com:Yelp/detect-secrets
  rev: v0.13.1 # https://github.com/Yelp/detect-secrets/releases
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline']

- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.31.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
